name = "axohub-registry"
version = "1.0.0"
license = "Apache-2.0"
description = "AxoHub smart contract registry validator"

[dependencies]
aiken-lang/stdlib = "1.9.0"

[[config.env]]
network = "preprod"
